language: go

go:
    - 1.8
    - 1.9
    - "1.10"

script:
    - cd vendor/github.com/satori/go.uuid/ && go test -bench=. && cd ../../../../
    - cd vendor/github.com/rcrowley/go-metrics/ && go test -benchmem -bench ^BenchmarkMeterParallel$

